diagnostic:
  run_dir: runs/diagnostic/3083
monitor:
  binary: true
  subtype: false
model:
  model: densenet
  pretrained: true
  params:
    drop_rate: 0.1
    dropout: 0.1
data:
  train:
  - name: rsna-no-match-sinoct-train
  val:
  - name: rsna-no-match-sinoct-val
  predict:
  - name: rsna-no-match-sinoct-test
  - name: bhx-all
training:
  epochs: 100
  batch_size: 256
  patience: 7
  eval_metric: auroc
  num_workers: 16
  pin_memory: true
  persistent_workers: true
  device: cuda
  use_sample_weights: false
optimizer:
  name: adamw
  lr: 5.0e-05
  lr_min: 1.0e-06
  weight_decay: 0.001
scheduler:
  name: cosine
loss:
  name: bce
  use_pos_weights: false
